### ISSUE TITLE
Package.json not displaying versions of all packages

### ISSUE THREAD

**Issue by thecodejack** [vscode-contrib/vscode-versionlens#127]
Package.json not displaying versions of all packages when one module's older version is invalid. I can see following error in dev tools console of vscode

```
[Extension Host] Error: NPM: parseNpmArguments TypeError: Invalid Version: 0.3.10.rc.0
	at /u/sri/.vscode/extensions/pflannery.vscode-versionlens-0.22.0/out/extension-bundle.js:1304:19
	at <anonymous>
	at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Expected behaviour should be to display versions of all packages even with this error

**Comment by thecodejack** [comment]
I checked the code, I think we shouldn't throw error here.
https://github.com/vscode-contrib/vscode-versionlens/blob/master/src/providers/npm/npmPackageParser.js#L71

 We should return just like 
https://github.com/vscode-contrib/vscode-versionlens/blob/master/src/providers/npm/npmPackageParser.js#L64

That should mostly fix the issue.
