### ISSUE TITLE
Clicking on a version to update it crashes the plugin

### ISSUE THREAD

**Issue by dylanvdmerwe** [vscode-contrib/vscode-versionlens#190]
![1](https://user-images.githubusercontent.com/2852839/81069033-9a8dee00-8ee1-11ea-8d99-665de5424fa7.gif)

```
[Extension Host] Error: NPM: parseNpmArguments Error: NPM: npmViewVersion Invalid Version: 1	at c:\Users\dylan\.vscode\extensions\pflannery.vscode-versionlens-0.26.1\out\extension-bundle.js:1919:19	at runMicrotasks (<anonymous>)	at processTicksAndRejections (internal/process/task_queues.js:85:5)	at runNextTicks (internal/process/task_queues.js:62:3)	at processImmediate (internal/timers.js:412:9)	at async Promise.all (index 40)
```

```
[Extension Host] Error: NPM: parseNpmArguments Error: NPM: npmViewVersion Invalid Version: 1	at c:\Users\dylan\.vscode\extensions\pflannery.vscode-versionlens-0.26.1\out\extension-bundle.js:1919:19	at async Promise.all (index 39)
```

```
[Extension Host] Error: NPM: parseNpmArguments Error: NPM: npmViewVersion Invalid Version: 1	at c:\Users\dylan\.vscode\extensions\pflannery.vscode-versionlens-0.26.1\out\extension-bundle.js:1919:19	at async Promise.all (index 2)
```

```
[Extension Host] Error: NPM: parseNpmArguments Error: NPM: npmViewVersion Invalid Version: 1	at c:\Users\dylan\.vscode\extensions\pflannery.vscode-versionlens-0.26.1\out\extension-bundle.js:1919:19	at runNextTicks (internal/process/task_queues.js:58:5)	at processImmediate (internal/timers.js:412:9)	at async Promise.all (index 55)
```

VS Code: 1.44.2
Version-lens: 0.26.1

**Comment by pflannery** [comment]
@dylanvdmerwe  This is fixed in 0.26.2. Let me know how it goes.
