### ISSUE TITLE
Activating extension `pflannery.vscode-versionlens` failed:  Cannot find module 'npm'

### ISSUE THREAD

**Issue by kurtextrem** [vscode-contrib/vscode-versionlens#50]
`[Extension Host] Here is the error stack:  Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Y.o._load (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:366355)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\admin\.vscode-insiders\extensions\pflannery.vscode-versionlens-0.13.0\out\src\providers\npm\npmCodeLensProvider.js:17:11)
    at Object.<anonymous> (C:\Users\admin\.vscode-insiders\extensions\pflannery.vscode-versionlens-0.13.0\out\src\providers\npm\npmCodeLensProvider.js:111:3)
    at Module._compile (module.js:571:32)
    at Module.i._compile (C:\Users\admin\.vscode-insiders\extensions\WallabyJs.quokka-vscode-1.0.31\dist\wallaby\client.js:14:28660)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Y.o._load (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:366355)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\admin\.vscode-insiders\extensions\pflannery.vscode-versionlens-0.13.0\out\src\extension.js:8:29)
    at Object.<anonymous> (C:\Users\admin\.vscode-insiders\extensions\pflannery.vscode-versionlens-0.13.0\out\src\extension.js:35:3)
    at Module._compile (module.js:571:32)
    at Module.i._compile (C:\Users\admin\.vscode-insiders\extensions\WallabyJs.quokka-vscode-1.0.31\dist\wallaby\client.js:14:28660)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)`

**Comment by pflannery** [comment]
@kurtextrem 
Looks like vscode didnt install the plugin properly.
I just tried a fresh install on vscode and vscode-insiders and its working for me.

So try this:

- Close vscode
- Delete the extension folder at C:\Users\admin\.vscode-insiders\extensions\pflannery.vscode-versionlens-0.13.0\
- Open vscode and install the extension fresh.

**Comment by kurtextrem** [comment]
That worked, thanks a lot. Very weird.
