### ISSUE TITLE
totally stop working with xunit cli reference

### ISSUE THREAD

**Issue by subn0wa** [vscode-contrib/vscode-versionlens#81]
Environment:
VS Code 1.15.1 (1.15.1)
MacOSX 10.12.5

How to reproduce:
>dotnet new xunit -o test
>cd test
>code .

open test.csproj and add `<DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta4-build3742" />` as shown in https://xunit.github.io/docs/getting-started-dotnet-core.html

Done. No more version lenses shown and "analyzing dependencies..." spinner will spin forever.

**Comment by pflannery** [comment]
I don't have a Mac. I'm not seeing this with VS Code 1.15.1 on Windows 10

Can you open dev tools and tell me if you see any errors in the console log.

![image](https://user-images.githubusercontent.com/1727302/29680245-e8ab5c42-88fb-11e7-8c61-a2f7204bef1e.png)

**Comment by dmccaffery** [comment]
@pflannery I was able to reproduce.

System:

ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

Visual Studio Code:

Version: 1.15.1
SHA: 41abd21afdf7424c89319ee7cb0445cc6f376959

<img width="1011" alt="dotnet-xunit-semver-error" src="https://user-images.githubusercontent.com/1803684/30005709-5344455c-909d-11e7-8f6c-f33a66e63c20.png">

TypeError: Invalid Version: undefined
    at new SemVer (/Users/deavon/.vscode/extensions/pflannery.vscode-versionlens-0.19.1/node_modules/semver/semver.js:279:11)
    at outside (/Users/deavon/.vscode/extensions/pflannery.vscode-versionlens-0.19.1/node_modules/semver/semver.js:1131:13)
    at Function.ltr (/Users/deavon/.vscode/extensions/pflannery.vscode-versionlens-0.19.1/node_modules/semver/semver.js:1120:10)
    at isOlderVersion (/Users/deavon/.vscode/extensions/pflannery.vscode-versionlens-0.19.1/out/extension-bundle.js:850:23)
    at Object.buildTagsFromVersionMap (/Users/deavon/.vscode/extensions/pflannery.vscode-versionlens-0.19.1/out/extension-bundle.js:995:87)
    at /Users/deavon/.vscode/extensions/pflannery.vscode-versionlens-0.19.1/out/extension-bundle.js:2891:48
    at process._tickCallback (internal/process/next_tick.js:103:7)
t.logExtensionHostMessage @ extensionHost.ts:335
(anonymous) @ extensionHost.ts:188
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

I don't see anything on the feed that would cause this issue, and I did verify that semver is able to parse the dotnet-xunit version:

<img width="433" alt="semver-dotnet-xunit" src="https://user-images.githubusercontent.com/1803684/30005742-fac4494e-909d-11e7-8478-1aee850591bd.png">
